feat: toggle room visibility
benawad/dogehouse pull request #124
Opened 2021-02-13 14:28 UTC by giuseppecampanelli

Quick way to allow room privacy toggling. Underlying code to switch between public & private can be cleaned up but I can only get to it later. If you need this out now, it has a first iteration.

2021-02-13 14:31 UTC, alii requested changes

2021-02-13 14:31 UTC, alii commented on kofta/src/vscode-webview/Routes.tsx
> +        }
You could convert this to a single line

```ts
toast(`Room is now ${isPrivate ? "private" : "public"}`, { type: "info" });
```

2021-02-13 14:31 UTC, benawad commented
oops didn't mean to change status, but looks good to me, let me know when you want merge

2021-02-14 01:33 UTC, giuseppecampanelli commented on kofta/src/vscode-webview/Routes.tsx
> +        }
Changed!

2021-02-14 01:36 UTC, giuseppecampanelli commented
@benawad ok to merge

2021-02-14 02:12 UTC, merged