localisation: add Austrian (AT) translation keys
benawad/dogehouse pull request #1315
Opened 2021-03-19 22:39 UTC by phiilu

Hey, I created a new folder `at` for the Austrian translations. 

Austrian is comparable to German, but we pronounce things differently. I also created the translations how we would talk (at least in Lower Austria / Vienna) in real life to each other (or at least I tried 😅 ). 

For my fellow Austrians if you find some better translations let me know and I will update them.

2021-03-19 22:53 UTC, jamesql commented
Please add this to the list in /kofta/src/app/components/LanguageSelector.tsx

2021-03-19 22:54 UTC, HMayotte requested changes
Looks good to me but make sure you add it to `LanguageSelector.tsx` similar to #1296.

2021-03-20 10:13 UTC, phiilu commented
Done added it to the LanguageSelector!

2021-03-20 13:02 UTC, HarrisonMayotte approved these changes

2021-03-20 13:03 UTC, merged