(Update) Add original Pogchamp emote
benawad/dogehouse pull request #1320
Opened 2021-03-19 23:15 UTC by ayaz-amin

Add original Pogchamp emote (w/ updated CONTRIBUTING.md).

2021-03-19 23:17 UTC, HMayotte approved these changes
Good work! Looks good!

2021-03-20 00:05 UTC, overlisted requested changes

2021-03-20 00:05 UTC, overlisted commented on CONTRIBUTING.md
> +Emojis need to be 28x28px. To add an emoji, add the png/gif image to public/emojis and add the emoji to the ```kofta/src/app/modules/room-chat/EmoteData.ts```.
Use `inline backticks`

```suggestion
Emojis need to be 28x28px. To add an emoji, add the png/gif image to public/emojis and add the emoji to the `kofta/src/app/modules/room-chat/EmoteData.ts`.
```

2021-03-20 01:29 UTC, HMayotte approved these changes

2021-03-20 05:25 UTC, ofsho commented
looks good

2021-03-20 05:27 UTC, merged