Add responsive design for SettingsIcon component
benawad/dogehouse pull request #1339
Opened 2021-03-20 05:40 UTC by banky

See https://github.com/benawad/dogehouse/issues/1324 for more details

Desktop: 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/8867230/111860321-24d61980-891d-11eb-99ac-f534b06e2ebd.png">

Mobile: 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/8867230/111860326-2dc6eb00-891d-11eb-8c3a-233600dca6f5.png">

2021-03-20 06:48 UTC, MadanBhandari approved these changes

2021-03-20 11:55 UTC, HMayotte approved these changes

2021-03-20 15:23 UTC, ajmnz requested changes

2021-03-20 15:23 UTC, ajmnz commented on kibbeh/src/ui/SettingsIcon.tsx
> +      w-full items-center px-4 py-2 cursor-pointer hover:bg-primary-700
Should be `py-3`

2021-03-21 01:54 UTC, banky commented on kibbeh/src/ui/SettingsIcon.tsx
> +      w-full items-center px-4 py-2 cursor-pointer hover:bg-primary-700
Gotcha, updated for `sm`

2021-03-21 01:56 UTC, HarrisonMayotte approved these changes
Appears to resolve issue from before.

2021-03-21 02:01 UTC, ajmnz commented
@HarrisonMayotte I’m no longer reviewing PRs, request Ben’s review from now on

2021-03-21 02:09 UTC, HarrisonMayotte commented
Sounds good @ajmnz. I'll remove you and add him instead.

2021-03-26 00:14 UTC, merged