Adds AccountOverlay mobile component
benawad/dogehouse pull request #1370
Opened 2021-03-20 14:02 UTC by sahilmob

2021-03-20 16:07 UTC, goldyydev requested changes
If you go on [this](https://www.figma.com/proto/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A65&scaling=min-zoom) mode you can see that the AccountOverlay is supposed to be a **draggable** overlay (with the handle at the top). you have made the div itself but did not make it draggable nor is it currently an overlay.

I'd suggest you use something like react-draggable for this.

2021-03-20 17:25 UTC, sahilmob commented
Yes it was clear for me that it is draggable, however, I focused only on the UI part of the component.
Anyway I will make draggable and update the PR.

2021-03-20 22:30 UTC, goldyydev requested changes
You took probably the most annoying component out there. hopefully this is the last fix 🤞 

![image](https://user-images.githubusercontent.com/55450464/111887271-7f827a80-89dc-11eb-94e6-3251701b96b0.png)

2021-03-20 22:35 UTC, sahilmob commented
@goldyydev No problem at all :smile:

2021-03-21 01:05 UTC, HarrisonMayotte approved these changes

2021-03-21 01:11 UTC, goldyydev requested changes
Just a minor fix

2021-03-21 01:11 UTC, goldyydev commented on kibbeh/src/ui/mobile/AccountOverlay.tsx
> +  axis = "both",
Just a minor fix, this wouldn't be used for any xy dragging.
```suggestion
  axis = "y",
```

2021-03-21 01:14 UTC, goldyydev approved these changes

2021-03-21 01:14 UTC, merged