Added MobileHeader Component UI
benawad/dogehouse pull request #1388
Opened 2021-03-20 18:45 UTC by PrinceRajRoy

Issue: #1324
Design: https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2250

2021-03-20 23:30 UTC, goldyydev requested changes
Just a minor issue but in the ProfileHeader, the Avatar is supposed to be larger by 10px than the icons.

2021-03-21 08:43 UTC, PrinceRajRoy commented
@goldyydev, yup but the rest of the predefined `SingleUser` sizes are a lot bigger, should I add a new one, `md` ?

2021-03-21 13:42 UTC, wes337 commented on kibbeh/src/stories/MobileHeader/ProfileHeader.story.tsx
> +  <div style={{ width: 420 }}>
I think you don't need to set this width in the story container, there is a "small/large mobile" view setting in storybook.

2021-03-21 15:16 UTC, ArnavBansal11 commented
> 
> 
> @goldyydev, yup but the rest of the predefined `SingleUser` sizes are a lot bigger, should I add a new one, `md` ?

size `xxs` of `SingleUser` is 30px which matches your requirements

2021-03-24 18:17 UTC, goldyydev commented
is there any progress on this?

2021-03-25 05:34 UTC, PrinceRajRoy commented
> is there any progress on this?

I have used xs on the Profile image, xxs is bigger than that, is it supposed to be like this? xxs >xs?
I will push the fix, if that's correct.

![snip](https://user-images.githubusercontent.com/47452572/112423918-851fed80-8d59-11eb-93aa-dfd990c39d5a.PNG)

2021-03-26 20:38 UTC, goldyydev commented
We really need it done, just make it work please.

2021-03-30 18:44 UTC, overlisted commented
what are we waiting for

2021-04-06 14:12 UTC, goldyydev commented
Come on....

2021-04-06 14:45 UTC, merged