Added FeaturedRoomCardHosts (#1324)
benawad/dogehouse pull request #1397
Opened 2021-03-20 20:47 UTC by BronzW

I've first of all added the FeaturedRoomCardHosts component (+story) in #1324  and I've made a temporary ``md`` until the implementation of it in #1390. I've also made it so the bigger the icons in ``MultipleUsers`` the further apart they are, for visibilty. When they are very small you don't really care that they are close together, but when they are big you almost cannot see the picture behind.

2021-03-20 22:39 UTC, goldyydev commented
FeaturedRoomCardAvatars does not seem to match the [Figma ](https://www.figma.com/file/CS01VVLR7ArQl0afYFkNj3/Web-App?node-id=4300%3A2338)design.

2021-03-21 08:34 UTC, BronzW commented
Yeah saw that, I'm going to fix that

2021-03-21 08:51 UTC, BronzW commented
Fixed it!

2021-03-21 09:10 UTC, BronzW commented
I'm done now.

2021-03-21 12:35 UTC, ajmnz commented
The square border is just for delimitation purposes, it shouldn't be there

2021-03-21 12:48 UTC, BronzW commented
There we go @ajmnz

2021-03-21 13:02 UTC, HarrisonMayotte approved these changes

2021-03-21 15:12 UTC, goldyydev commented
The text does not appear to be centered, that cold cause us issues in the future.
![image](https://user-images.githubusercontent.com/55450464/111910082-9a9acc00-8a68-11eb-82d6-bc52c4cb3d0c.png)

2021-03-21 15:29 UTC, BronzW commented
@goldyydev Fixed it

2021-03-21 17:50 UTC, BronzW commented
Anyone? I'm feeling lonely and scared

2021-03-21 19:26 UTC, goldyydev requested changes

2021-03-21 19:26 UTC, goldyydev commented on kibbeh/src/ui/mobile/FeaturedRoomCardHosts.tsx
> +};
```suggestion
}; 

```

2021-03-21 19:26 UTC, goldyydev commented on kibbeh/src/ui/mobile/FeaturedRoomCardAvatars.tsx
> +};
```suggestion
}; 

```

2021-03-21 19:26 UTC, goldyydev commented on kibbeh/src/stories/mobile/FeaturedRoomCardHosts.story.tsx
> +export const OneHost = One.bind({})
```suggestion
export const OneHost = One.bind({});

```

2021-03-21 19:26 UTC, goldyydev commented on kibbeh/src/stories/mobile/FeaturedRoomCardAvatars.story.tsx
> +export const OneAvatar = One.bind({})
```suggestion
export const OneAvatar = One.bind({});
```

2021-03-21 19:27 UTC, merged