Improve English Translations
benawad/dogehouse pull request #1694
Opened 2021-03-31 06:30 UTC by MMK21Hub

- Better coverage for `en-pirate`
- Fix capitalisation in `en`
- Reword a few strings to make more sense
- Grammar fixes

2021-03-31 09:34 UTC, overlisted commented
also consider adding these changes to the owo language

2021-03-31 13:58 UTC, benawad requested changes

2021-03-31 13:58 UTC, benawad commented on kofta/public/locales/en/translation.json
> +        "deleteMessage": "",
Any reason you left this blank?

2021-03-31 15:05 UTC, MMK21Hub commented on kofta/public/locales/en/translation.json
> +        "deleteMessage": "",
Didn't mean to do that; I'll fix it.

2021-03-31 16:00 UTC, MMK21Hub commented on kofta/public/locales/en/translation.json
> +        "deleteMessage": "",
Resolved by 225e2f6

2021-04-01 06:45 UTC, MMK21Hub commented
> also consider adding these changes to the owo language

Marked this as a draft to let me do this

2021-04-04 16:58 UTC, noftaly commented on kofta/public/locales/en-pirate/translation.json
> +      "loginGithub": "Set Sail wit' with GitHub",
```suggestion
      "loginGithub": "Set Sail wit' GitHub",
```

2021-04-06 10:47 UTC, amitojsingh366 commented
whats the status on this @MMK21Hub?

2021-04-06 12:18 UTC, MMK21Hub commented
> whats the status on this MMK21Hub?

@amitojsingh366 It's been on my to-do list for a while, I'm planning to work on it today and tomorrow. Should be ready to merge by then.

2021-04-06 12:18 UTC, MMK21Hub commented on kofta/public/locales/en-pirate/translation.json
> +      "loginGithub": "Set Sail wit' with GitHub",
Thanks for spotting that mistake!

2021-04-06 12:21 UTC, MMK21Hub commented
> also consider adding these changes to the owo language

Done with 8975a3f

2021-04-09 18:14 UTC, merged