Add the "BaseDropdownSm" component
benawad/dogehouse pull request #2039
Opened 2021-04-15 16:13 UTC by Ongshu777

2021-04-15 16:16 UTC, HonbraDev approved these changes

2021-04-15 18:15 UTC, goldyydev requested changes
Can you please add a hover effect to the items?

2021-04-15 20:56 UTC, Ongshu777 commented
@goldyydev Is this fine? 
![image](https://user-images.githubusercontent.com/51079288/114937172-5b785480-9e35-11eb-887a-eef9e25db1f6.png)

2021-04-16 21:36 UTC, goldyydev commented
Awesome! Aaand straight to staging it goes

2021-04-16 21:36 UTC, merged