Added ProfileAbout component (redesign)
benawad/dogehouse pull request #2075
Opened 2021-04-16 18:20 UTC by BronzW

#2022

2021-04-16 19:00 UTC, dk-raw commented
Why did you made a pr then?

2021-04-16 21:33 UTC, goldyydev commented
> ~~Please don't merge this yet as I want to add responsiveness to this component.~~

Does this mean that I can merge it or not?

2021-04-17 06:48 UTC, dk-raw commented
> > ~Please don't merge this yet as I want to add responsiveness to this component.~
> 
> Does this mean that I can merge it or not?

I guess so

2021-04-17 08:36 UTC, BronzW commented
Yes. I added responsiveness in https://github.com/benawad/dogehouse/pull/2075/commits/aa35422bba8cf033708f6fa0406b94bce6db58dd

2021-04-17 14:10 UTC, goldyydev requested changes

2021-04-17 14:10 UTC, goldyydev commented on kibbeh/src/ui/ProfileAbout.tsx
> +}
```suggestion
}

```

2021-04-17 14:10 UTC, merged