UpcomingRoomCardLg component
benawad/dogehouse pull request #2088
Opened 2021-04-17 08:21 UTC by sahilmob

#2022

2021-04-17 12:05 UTC, goldyydev commented
Just a few things:
@ajmnz the europeanos are offended by the MM/DD/YYYY format.
![image](https://user-images.githubusercontent.com/55450464/115112439-4236eb80-9f8e-11eb-900c-4f32ee871250.png)

@sahilmob shouldn't the tags be <Tag> elements? in the future we'll need to add glows to them and emotes.

2021-04-17 12:14 UTC, TheOtterlord commented
> @ajmnz the europeanos are offended by the MM/DD/YYYY format.

can confirm, this is really annoying 🙂

2021-04-17 12:15 UTC, ajmnz commented
> Just a few things:
> @ajmnz the europeanos are offended by the MM/DD/YYYY format.
> ![image](https://user-images.githubusercontent.com/55450464/115112439-4236eb80-9f8e-11eb-900c-4f32ee871250.png)
> 
> @sahilmob shouldn't the tags be elements? in the future we'll need to add glows to them and emotes.

Can confirm, I am from Europe (12h format bothers me too), but I cannot make that dynamic on Figma. It should take into consideration the users location

2021-04-17 13:33 UTC, sahilmob commented
@goldyydev What do you mean by elements? I used the Tag component the is mentioned under `UpcomingRoomCardLg` pre-requisites in #2022.

Also I didn't mean to offend anybody. I just wanted to be as close a possible to the design.

2021-04-17 13:35 UTC, ajmnz commented
> Also I didn't mean to offend anybody. I just wanted to be as close a possible to the design.

You definitely didn't offend anybody, it's just that it'd be great if the date structure could be determined by the user's location

2021-04-17 16:09 UTC, sahilmob commented
I will try to find an easy solution to format the time based on the user location

2021-04-17 16:22 UTC, goldyydev commented
> I will try to find an easy solution to format the time based on the user location

Maybe we can display it as `MMM DD, HH:MM` (Jan 1, 00:00)

2021-04-17 19:07 UTC, sahilmob commented
> > I will try to find an easy solution to format the time based on the user location
> 
> Maybe we can display it as `MMM DD, HH:MM` (Jan 1, 00:00)

I can change the format `MMM DD, HH:MM` if everybody is okay with it.

2021-04-18 01:42 UTC, Mvrs commented
@sahilmob 
I noticed something... it's a small issue, but very noticeable, the header title for the card doesn't have a font weight. Just add `font-bold` and that'll give it the correct value: **700**.

2021-04-18 05:37 UTC, sahilmob commented
> @sahilmob
> I noticed something... it's a small issue, but very noticeable, the header title for the card doesn't have a font weight. Just add `font-bold` and that'll give it the correct value: **700**.

done

2021-04-19 17:41 UTC, ajmnz requested changes
While you're at it, could you change the `Tag` and `Button/small` text size from `text-xs` to `text-sm`?

2021-04-19 17:41 UTC, ajmnz commented on kibbeh/src/ui/UpcomingRoomCardLg.tsx
> +        Add to calender
```suggestion
        Add to calendar
```

2021-04-19 20:47 UTC, ajmnz approved these changes
Looks good!

2021-04-19 20:47 UTC, merged