Update UserProfileController.tsx
benawad/dogehouse pull request #2575
Opened 2021-05-05 18:00 UTC by avipars

https://github.com/benawad/dogehouse/issues/2574

Fixed the lowercase to uppercase... 

I hope i can contribute more in the future... this is certainly a small step.

2021-05-05 23:08 UTC, amitojsingh366 commented
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

2021-05-06 18:04 UTC, wes337 requested changes

2021-05-06 18:04 UTC, wes337 commented on kibbeh/src/modules/user/UserProfileController.tsx
> +            Privacy Settings
This should be added to the translations

2021-05-06 18:14 UTC, amitojsingh366 commented
@nadirabbas has already added translation keys for this

2021-05-06 18:14 UTC, closed without merging