made room:get_info send more info
benawad/dogehouse pull request #2644
Opened 2021-05-07 22:49 UTC by amitojsingh366

- made `room:get_info` send more info

2021-05-07 23:28 UTC, overlisted requested changes

2021-05-07 23:28 UTC, overlisted commented on kebab/src/websocket/wrapper.ts
> +      connection.sendCall("room:get_info", { roomId })
```suggestion
      connection.sendCall("room:get_info", { roomId }),
```

2021-05-07 23:30 UTC, overlisted approved these changes

2021-05-08 02:03 UTC, benawad commented
Something else is planned for this, wait

2021-05-08 02:03 UTC, closed without merging