Gif Search in chat room
benawad/dogehouse pull request #2695
Opened 2021-05-10 23:31 UTC by NickersWeb

Left api key for giphy in the `libs/constants.js` ... change it to another api key when production. 
Left the ability to select a gif with an alert... not sure how you guys would want to handle this. Potentially a message type property that will illustrate it being a gif.

2021-05-10 23:38 UTC, amitojsingh366 commented
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

2021-05-10 23:39 UTC, amitojsingh366 commented
please don't use npm in kebab, all of our workspaces use yarn. also im not sure if we need a gif picker rn and if we do i don't think you did this the right way, you should probably create a new message token and pass it as that

2021-05-10 23:54 UTC, willdoescode requested changes
Rewrite in rust

2021-05-11 00:00 UTC, samarmohan commented
> Rewrite in rust

lol but be serious please

2021-05-11 00:00 UTC, samarmohan commented
Make sure all checks pass so we can merge. Your code is fine, style/guidelines are not.

2021-05-11 00:04 UTC, willdoescode commented
> > Rewrite in rust
> 
> lol but be serious please

😎

2021-05-11 00:08 UTC, benawad commented
idk if I want gifs in chat (I'm leaning towards no and being a twitch chat), but let me think about it

2021-05-11 00:08 UTC, willdoescode commented
> idk if I want gifs in chat (I'm leaning towards no and being a twitch chat), but let me think about it

I agree with ben, you should also rewrite in rust

2021-05-11 00:18 UTC, samarmohan requested changes
Do we actually need this? @benawad

2021-05-11 05:44 UTC, Odyssey346 commented
> 
> 
> > idk if I want gifs in chat (I'm leaning towards no and being a twitch chat), but let me think about it
> 
> I agree with ben, you should also rewrite in rust

Nah, we will rewrite it in C#.

2021-05-11 09:29 UTC, NickersWeb commented
Happy to work towards the guidelines. Just a thought, perhaps this could be a room setting by the admin after they have created the room.

2021-05-11 12:46 UTC, overlisted requested changes
Use ESLint and Prettier please

2021-05-11 12:46 UTC, overlisted commented on kebab/src/entities.ts
> +//enums
```suggestion
// enums
```

2021-05-11 12:46 UTC, overlisted commented on kebab/src/entities.ts
> +}
```suggestion
};

```

2021-05-11 12:46 UTC, overlisted commented on kebab/src/entities.ts
> +}
```suggestion
};
```

2021-05-11 12:46 UTC, overlisted commented on kebab/src/http/giphy.ts
> +};
```suggestion
export const giphy = (apiKey: string) => ({
        trendingGifs: (limit: number, rating: GifRating) =>
            create({
                baseUrl: 'https://api.giphy.com/v1/gifs/'
            }).request('GET', `trending?api_key=${apiKey}&limit=${limit}&rating=${rating}`) as Promise<{
                data: GifResponse[]
            }>,
        queryGifs: (query: string, limit: number, rating: GifRating) =>
            create({
                baseUrl: 'https://api.giphy.com/v1/gifs/'
            }).request('GET', `search?api_key=${apiKey}&q=${query}&limit=${limit}&rating=${rating}`) as Promise<{
                data: GifResponse[]
            }>
});
```

2021-05-11 12:46 UTC, overlisted commented on kebab/src/http/giphy.ts
> +};
what is this indentation

2021-05-11 12:46 UTC, overlisted commented on kebab/src/http/index.ts
> +export * from './giphy';
```suggestion
export * from "./giphy";
```

2021-05-11 16:35 UTC, overlisted commented on kebab/package.json
> +}
```suggestion
}

```

2021-05-11 16:36 UTC, overlisted commented on kebab/src/entities.ts
> +}
```suggestion
}
```

2021-05-11 16:38 UTC, overlisted commented on kebab/src/http/giphy.ts
> +            }>
```suggestion
  trendingGifs: (limit: number, rating: GifRating) =>
    create({
      baseUrl: 'https://api.giphy.com/v1/gifs/'
    }).request('GET', `trending?api_key=${apiKey}&limit=${limit}&rating=${rating}`) as Promise<{
      data: GifResponse[]
    }>,
  queryGifs: (query: string, limit: number, rating: GifRating) =>
    create({
      baseUrl: 'https://api.giphy.com/v1/gifs/'
    }).request('GET', `search?api_key=${apiKey}&q=${query}&limit=${limit}&rating=${rating}`) as Promise<{
      data: GifResponse[]
    }>
```

2021-05-11 19:06 UTC, overlisted approved these changes

2021-05-11 19:55 UTC, benawad commented
decided I don't want this

2021-05-11 19:55 UTC, closed without merging