feat: add admin tab to user profile
benawad/dogehouse pull request #2728
Opened 2021-05-12 22:30 UTC by amitojsingh366

2021-05-12 22:31 UTC, overlisted approved these changes

2021-05-13 00:29 UTC, benawad requested changes

2021-05-13 00:29 UTC, benawad commented on kousa/lib/kousa/user.ex
> +    if admin.staff == true or admin.githubId == authorized_github_id do
add a test for this logic

2021-05-13 00:37 UTC, amitojsingh366 commented on kousa/lib/kousa/user.ex
> +    if admin.staff == true or admin.githubId == authorized_github_id do
done

2021-05-13 03:31 UTC, merged