Translation nl
benawad/dogehouse pull request #2737
Opened 2021-05-13 13:48 UTC by plunched

added some translations to dutch | nl

2021-05-13 13:52 UTC, plunched commented
gotta resolve the conflicts I guess

2021-05-13 13:56 UTC, plunched commented
will do more later on

2021-05-13 13:57 UTC, overlisted approved these changes

2021-05-13 14:11 UTC, samarmohan approved these changes

2021-05-13 14:19 UTC, amitojsingh366 commented
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

2021-05-15 19:13 UTC, DoeHetGewoon requested changes
Maybe change some things

2021-05-15 19:13 UTC, DoeHetGewoon commented on kibbeh/public/locales/nl/translation.json
> +    "requestPermissions": "Hou er rekening mee dat het uitvoeren van DogeHouse zonder de benodigde permissies ongewenste fouten kan veroorzaken"
The old line is more formal Dutch

2021-05-15 19:13 UTC, DoeHetGewoon commented on kibbeh/public/locales/nl/translation.json
> -      "privacySettings": "Privacy settings"
Why is this gone?

2021-05-15 19:13 UTC, DoeHetGewoon commented on kibbeh/public/locales/nl/translation.json
> +      "goHomeMessage": "Maak je geen zorgen. Je kan naar de homePagina gaan",
home-pagina*

2021-05-15 19:13 UTC, DoeHetGewoon commented on kibbeh/public/locales/nl/translation.json
> +    "deafenedTitle": "dedempt | DogeHouse",
Typing error

2021-05-21 15:55 UTC, amitojsingh366 commented
stale pr, gonna close

2021-05-21 15:55 UTC, closed without merging