feat(kibbeh): added language search
benawad/dogehouse pull request #2744
Opened 2021-05-13 20:46 UTC by firecraftgaming

2021-05-13 20:46 UTC, firecraftgaming commented
![image](https://user-images.githubusercontent.com/42218879/118185679-1861cf00-b43d-11eb-8edc-5ff9a10fba9e.png)

2021-05-13 20:57 UTC, amitojsingh366 commented on kibbeh/package.json
> +    "tsc": "^2.0.3",
add this in dev deps

2021-05-13 20:58 UTC, amitojsingh366 requested changes

2021-05-13 20:58 UTC, amitojsingh366 commented on kibbeh/package.json
> +    "tsc": "^2.0.3",
add this in dev deps

2021-05-13 20:58 UTC, amitojsingh366 commented on kibbeh/package.json
> +    "yarn": "^1.22.10",
please don't keep this in the deps at all

2021-05-13 21:06 UTC, amitojsingh366 commented
please follow the proper pattern for commit messages *(💡TIP: you can use `yarn commit` or `yarn commit:signed` and answer the questions asked to generate a properly formatted one for you!)*

to fix your most recent commit you can run the command `git commit --amend -m "properly formatted commit message here"`

to fix your older/multiple commits please take a look at [this article](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages)

2021-05-13 22:41 UTC, amitojsingh366 requested changes
also you made the search case sensitive, it shouldn't be like that. i want to be able to type in "english" to get the suggestion for English. rn i need to type the "E" capital

2021-05-13 22:41 UTC, amitojsingh366 commented on kibbeh/src/ui/LanguageSearch.tsx
> +  flex w-full items-center px-4 py-4 md:py-2 cursor-pointer md:hover:bg-primary-700
remove the `cursor-pointer` class

2021-05-13 22:42 UTC, amitojsingh366 commented
also i don't think search bar color should change on hover

2021-05-14 17:09 UTC, samarmohan approved these changes

2021-05-14 20:14 UTC, ajmnz approved these changes
This will probably get wiped at some point, but it's fine for now

2021-05-14 20:49 UTC, merged