feat: delete chat messages
benawad/dogehouse pull request #417
Opened 2021-02-25 09:27 UTC by nadirabbas

| Entity | Can delete |
| ------------- | ------------- |
| Room creators  | `own`, `mods`, `listeners` messages |
| Mods  | `own`, `listeners` messages  |
| Listeners | `own` messages  |

Creators and Mods can delete all messages of a particular user at once

| Action | View |
| ------------- | ------------- |
| Delete own message  | ![image](https://user-images.githubusercontent.com/38838675/109131821-f7121080-7774-11eb-863b-3b72afbdb0b2.png) |
| Delete someone else's message  | ![image](https://user-images.githubusercontent.com/38838675/109131761-e6fa3100-7774-11eb-845c-70215c5564a0.png) |
| Click menu on own message  | ![image](https://user-images.githubusercontent.com/38838675/109132006-2fb1ea00-7775-11eb-9daa-b72cfc14352e.png) |
| Click menu on someone else's message  | ![image](https://user-images.githubusercontent.com/38838675/109132143-51ab6c80-7775-11eb-81a0-59138db27f49.png)|

***ONLY CREATORS/MODS CAN DELETE OTHER PEOPLE'S MESSAGES

2021-02-25 15:03 UTC, nadirabbas commented
@benawad  conflicts resolved

2021-02-25 16:27 UTC, benawad commented
1. DogeHouse will be getting a redesign, until then just stick the delete button inside the profile modal instead of adding tooltip +framer motion 
2. This is missing server-side authorization logic. Get the status of each user server-side: https://github.com/benawad/dogehouse/blob/staging/kousa/lib/business-logic/room_logic.ex#L94 and make sure the deleter has higher permission level

2021-02-25 16:29 UTC, nadirabbas commented
Okay I will add server-side validation. But I didn't understand the first point, how will we delete a particular message from the profile modal?

2021-02-25 16:44 UTC, benawad commented
You'll have to add some props to it for message id so you know which one to delete

2021-02-25 20:01 UTC, nadirabbas commented
@benawad Please review the changes when you get the time.

2021-02-26 02:49 UTC, benawad requested changes
overall, looking really good

2021-02-26 02:49 UTC, benawad commented on kofta/package.json
> +    "framer-motion": "^3.7.0",
you can remove the deps

2021-02-26 02:49 UTC, benawad commented on kousa/lib/business-logic/room_chat_logic.ex
> +        if user_id != room.creatorId do
this allows mods to delete other mods messages. I'm ok with this so we can avoid more DB queries, but can you add a comment about this

2021-02-26 02:49 UTC, benawad commented on kousa/lib/gen/room_chat.ex
> +    if not Map.has_key?(state.ban_map, user_id) and
I don't think you need to check ban_map and I wouldn't worry about throttling deletes

2021-02-26 02:49 UTC, benawad commented on kousa/lib/gen/room_chat.ex
> +    if not Map.has_key?(state.ban_map, deleter_id) and
same as above

2021-02-26 18:10 UTC, merged

2021-02-26 18:13 UTC, benawad commented
are you able to run the elixir server locally? It had some small compiler errors when I tried locally that I fixed real quick.

2021-02-26 18:16 UTC, nadirabbas commented
@benawad really sorry! I made these changes in the Github editor, figured they are pretty simple 😅

2021-02-26 18:16 UTC, nadirabbas commented
what was the mistake?

2021-02-26 18:18 UTC, benawad commented
Just a missing `}`, if you use VSCode, install ElixirLS too