Implement Feed component
benawad/dogehouse pull request #786
Opened 2021-03-12 22:25 UTC by yvesnrb

This PR implements the Feed component and associated story.

2021-03-12 22:42 UTC, ajmnz requested changes
I think user-subscribed scheduled rooms should be on top, but how would you like to go about this? @benawad

2021-03-12 22:44 UTC, yvesnrb commented
> I think user-subscribed scheduled rooms should be on top, but how would you like to go about this? @benawad

In that case, should I just add a 'subscribed' boolean to the props interface of Feeds to handle that logic and let whatever is referencing the Feed component handle it?

2021-03-12 22:47 UTC, ajmnz commented
> > I think user-subscribed scheduled rooms should be on top, but how would you like to go about this? @benawad
> 
> In that case, should I just add a 'subscribed' boolean to the props interface of Feeds to handle that logic and let whatever is referencing the Feed component handle it?

Kind of, because maybe we don't want to show more than x scheduled rooms or only rooms that are scheduled for today.

2021-03-12 22:52 UTC, yvesnrb commented
> > > I think user-subscribed scheduled rooms should be on top, but how would you like to go about this? @benawad
> > 
> > 
> > In that case, should I just add a 'subscribed' boolean to the props interface of Feeds to handle that logic and let whatever is referencing the Feed component handle it?
> 
> Kind of, but maybe we don't want to show more than x scheduled rooms or only rooms that are scheduled for today.

Got it. Just let me now how the feed should work @benawad and I'll make the necessary changes.

2021-03-12 23:27 UTC, benawad commented on kibbeh/src/ui/Feed.tsx
> +  }, [rooms]);
`Feed` don't use useEffect and store rooms in state. Take rooms as a prop. Also don't worry about scheduled rooms for now until the mockup is done for that

2021-03-13 01:13 UTC, yvesnrb commented
I left the divider commented out for later and just mapped trough the rooms prop for now.

2021-03-13 01:15 UTC, benawad approved these changes

2021-03-13 01:15 UTC, merged